#!/bin/bash
clear
url=$1
echo "All-in-one Download Script for Termux"
echo "--------------------------------------------"
echo "1: Download with yt-dlp (Fixed Bandwidth Throttling by YouTube)"
echo "2: Download with ffmpeg(m3u8/m3u)"
echo "3: Download with wget (Recursive)"
echo "4: Download with spotdl (Spotify All-in-one)"
echo "5: Download with yt-dlp and extract audio (Fixed Bandwidth Throttling by YouTube)"
echo "6: Download with yt-dlp and extract audio with thumbnail"
echo "Default: Download with yt-dlp (Fixed Bandwidth Throttling by YouTube)"
read n

if [ "$n" == '2' ]; then
echo "Output Filename:"
read name
ffmpeg -i "$url" -c copy -bsf:a aac_adtstoasc "/data/data/com.termux/files/home/storage/downloads/$name"
else

if [ "$n" == '3' ]; then
wget -P "/data/data/com.termux/files/home/storage/downloads/" -c --mirror  --recursive --no-clobber  --page-requisites --html-extension --convert-links -e robots=off --restrict-file-names=windows --no-parent "$url"
else

if [ "$n" == '4' ]; then 
[ ! -d "/data/data/com.termux/files/home/storage/downloads/spotdl" ] && mkdir "/data/data/com.termux/files/home/storage/downloads/spotdl"
test -f  "/data/data/com.termux/files/home/.spotdl_playlist"  && rm "/data/data/com.termux/files/home/.spotdl_playlist.txt"
test -f  "/data/data/com.termux/files/home/.spotdl_album"  && rm "/data/data/com.termux/files/home/.spotdl_album.txt"
[[ $url == *"track"* ]] && spotdl --output-file "/data/data/com.termux/files/home/storage/downloads/spotdl/{artist} - {track-name}.{output-ext}" --song "$url" -q best --output-ext mp3
[[ $url == *"playlist"* ]] && spotdl --playlist "$url" --write-to  "/data/data/com.termux/files/home/.spotdl_playlist.txt"  && spotdl --output-file "/data/data/com.termux/files/home/storage/downloads/spotdl/{artist} - {track-name}.{output-ext}" --list "/data/data/com.termux/files/home/.spotdl_playlist.txt" -q best --output-ext mp3 && rm -f "/data/data/com.termux/files/home/.spotdl_playlist.txt"
[[ $url == *"album"* ]] && spotdl --album "$url" --write-to  "/data/data/com.termux/files/home/.spotdl_album.txt" && spotdl --output-file "/data/data/com.termux/files/home/storage/downloads/spotdl/{artist} - {track-name}.{output-ext}" --list "/data/data/com.termux/files/home/.spotdl_album.txt" -q best --output-ext mp3 && rm -f "/data/data/com.termux/files/home/.spotdl_album.txt"
else

if [ "$n" == '5' ]; then
[ ! -d "/data/data/com.termux/files/home/storage/downloads/Youtube" ] && mkdir "/data/data/com.termux/files/home/storage/downloads/Youtube"
yt-dlp --extractor-args "youtube:player_client=android" -x --audio-format mp3 -f bestaudio --audio-quality 0 -c -i "$url" -o "/data/data/com.termux/files/home/storage/downloads/Youtube/%(title)s.%(ext)s"
else

if [ "$n" == '6' ]; then
[ ! -d "/data/data/com.termux/files/home/storage/downloads/Youtube" ] && mkdir "/data/data/com.termux/files/home/storage/downloads/Youtube"
yt-dlp --extractor-args "youtube:player_client=android" -x --audio-format mp3 -f bestaudio --audio-quality 0  --add-metadata --ffmpeg-location /data/data/com.termux/files/usr/bin/ffmpeg --embed-thumbnail --ppa "EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\"" -c -i "$url" -o "/data/data/com.termux/files/home/storage/downloads/Youtube/%(title)s.%(ext)s"
else

[ ! -d "/data/data/com.termux/files/home/storage/downloads/Youtube" ] && mkdir "/data/data/com.termux/files/home/storage/downloads/Youtube"
yt-dlp  --extractor-args "youtube:player_client=android" -c -i "$url" -o "/data/data/com.termux/files/home/storage/downloads/Youtube/%(title)s.%(ext)s"
fi
fi
fi
fi
fi
